### ISSUE TITLE
error with lj-vm-states:

### ISSUE THREAD

**Issue by rshriram** [openresty/stapxx#22]
On ubuntu 14.04 with 3.16.0-30-generic kernel, systemtap 2.6 installed and stock openresty compilation from https://github.com/openresty/docker-openresty/blob/master/trusty/Dockerfile

I just added these two compiler flags to that build script:
``` 
 --with-luajit-xcflags='-O3' \
 --with-cc-opt='-O3' \
```

When I run the lj-vm-states, I get this error:
`ERROR: read fault [man error::fault] at 0x00007f1af6071008 (addr) near operator '@cast' at stapxx-EB6am9qD/nginx.config.stp:7:11`

Any idea what might be the issue?

**Comment by agentzh** [comment]
@rshriram Usually such read faults are harmless since systemtap can step in at *any* time during the execution of your target process and the memory layout in that process at that particular time instant could be inconsistent, which is completely normal and expected.

You can try adding the `--skip-badvars` option to your `lj-vm-states` command line to ignore this.

**Comment by rshriram** [comment]
The problem is that the script terminates immediately, without producing the desired output.

```bash
root@myhost:~/stapxx# ./samples/lj-vm-states.sxx -x 5796 
Found exact match for libluajit: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0
Start tracing 5796 (/usr/sbin/nginx)
Hit Ctrl-C to end.
ERROR: read fault [man error::fault] at 0x00007f4ec23de038 (addr) near operator '@cast' at stapxx-ipPMMYk9/nginx.config.stp:7:11
WARNING: Number of errors: 1, skipped probes: 0
WARNING: /opt/stap/bin/staprun exited with status: 1
Pass 5: run failed.  [man error::pass5]
```

**Comment by rshriram** [comment]
the `--skip-badvars` worked. Thanks!
