### ISSUE TITLE
how to trace redis sock:receive() timeout

### ISSUE THREAD

**Issue by redcloser** [openresty/stapxx#27]
redis and the openresty server are in the same compute,
the redis cmd is very very easy cmd ,it will not take more than 1sec aways 20ms in the redis slowlog list

resty/redis.lua
local function _read_reply(self, sock)
    local start_time = ngx.time()
    local line, err = sock:receive()
    local cost_time = ngx.time() - start_time
end

the cost_time sometimes greater than 1sec, i don't know how to trace this probleam,can you give me some advice?
thanks!

**Comment by agentzh** [comment]
@redcloser Trouble shooting timeout or long latency issues can be complicated to explain since many factors may weight in. I don't have the time right now to do the lengthy explanation and tutorial right here. Better watch your processes' CPU usage, accept/receive queue of your OS's network stack, and etc. When some hardware resource is exhausted, some software just cannot handle events fast enough. You can find relevant tools in either this repository or the openresty-systemtap-toolkit repository.

**Comment by agentzh** [comment]
@redcloser Both on-CPU and off-CPU flame graphs can be helpful in trouble-shooting blocking things due to CPU computations or some blocking (I/O) syscalls.

**Comment by redcloser** [comment]
thanks very much, 

this sample code is the same model like the code in real world Lua applications, huge cpu calculate then redis:cmd()

 sock:receive cost time is 15s,
i don't know why after huge cpu calculate affect sock:receive function

```
local sum = 0
for i = 1, 100000000 do
    sum = (sum + i) % 10
end
local res, err = redis:set("key", 1) 
```

```
resty/redis.lua
local function _read_reply(self, sock)
local start_time = ngx.time()
local line, err = sock:receive()
local cost_time = ngx.time() - start_time  #cost_time=15s
end
```

**Comment by agentzh** [comment]
@redcloser You should avoid intensive CPU calculations to block your nginx event loop for a long time. For many concurrent requests, request A's CPU computation will block request B's redis I/O. They're sharing the same OS thread in the same nginx worker process. So it's your responsibility to either avoid the intensive CPU calculations in the first place or manually yield from time to time in the middle of your CPU calculation via calls like `ngx.sleep(0.001)`. We'll soon introduce a delay-free yielding API for this so that you don't need to introduce a 1 ms delay every time you use `ngx.sleep` to yield voluntarily.

**Comment by redcloser** [comment]
thank you so much~ :)
